apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: jenkins-agent
      image: jenkins/jnlp-agent:latest
      args:
        - '${JENKINS_URL}'
        - '${AGENT_NAME}'
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "500Mi"
          cpu: "500m"
      volumeMounts:
        - name: jenkins-workspace
          mountPath: /home/jenkins/agent
    - name: maven
      image: maven:3.8.4
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "500Mi"
          cpu: "500m"
      volumeMounts:
        - name: jenkins-workspace
          mountPath: /home/jenkins/agent
    - name: helm
      image: alpine/helm:3.7.0
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "500Mi"
          cpu: "500m"
      volumeMounts:
        - name: jenkins-workspace
          mountPath: /home/jenkins/agent
  volumes:
    - name: jenkins-workspace
      emptyDir: {}
