pipeline {
    agent {
        kubernetes {
            yamlFile 'dply/build-pod.yaml'
            defaultContainer 'jenkins-agent'
        }
    }

    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Deploy') {
            steps {
                container('maven') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}
